[nfs]
18.218.34.200 ansible_ssh_user='ec2-user'

[webservers]
18.116.47.50 ansible_ssh_user='ec2-user'
172.31.4.223 ansible_ssh_user='ec2-user'

[db]
172.31.13.193 ansible_ssh_user='ubuntu' 

[lb]
18.188.251.36 ansible_ssh_user='ubuntu'